name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Lua 5.4 and development headers
      run: |
        sudo apt update
        sudo apt install -y lua5.4 liblua5.4-dev g++ make

    - name: Initialize submodules (e.g., LuaBridge if used)
      run: git submodule update --init --recursive

    - name: Build project with Makefile
      run: |
        cd src
        make